apiVersion: v1
kind: Service
metadata:
  name: byteboard-ui
  labels:
    app: byteboard-ui
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30003
      protocol: TCP
  selector:
    app: byteboard-ui
